services:
  # Full-stack Web Service (Serves both frontend and backend)
  - type: web
    name: pharmasmart-fullstack
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start --prefix backend
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://postgres.dcspovbsftfvujtnbrln:Pharmcysmart20@aws-1-eu-central-1.pooler.supabase.com:5432/postgres
      - key: JWT_SECRET
        value: default_dev_secret
